# -*- coding: utf-8 -*-
"""Untitled98.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1eEJOSomn7ZVWwXUYCpZRgO8G1CEvKcWq
"""

import requests
import pandas as pd
from xml.etree import ElementTree as ET
from bs4 import BeautifulSoup

def fetch_eydap_reservoir_rss() -> pd.DataFrame:
    """
    Fetch extractable reservoir stock data from EYDAP RSS feed.
    Covers: Εύηνος, Μαραθώνας, Μόρνος, Υλίκη — updated daily, last 31 days.
    """
    url = "https://www.eydap.gr/handlers/rss.ashx?collection=WaterProduction&Culture=69"
    response = requests.get(url, headers={"User-Agent": "Mozilla/5.0"})
    response.raise_for_status()

    root = ET.fromstring(response.content)
    description_html = root.find(".//item/description").text

    soup = BeautifulSoup(description_html, "html.parser")
    table = soup.find("table")

    headers, rows = None, []
    for tr in table.find_all("tr"):
        cells = [td.get_text(strip=True) for td in tr.find_all(["th", "td"])]
        if headers is None:
            headers = cells
        else:
            rows.append(cells)

    df = pd.DataFrame(rows, columns=headers)

    df = df.rename(columns={
        "ΗΜΕΡΟΜΗΝΙΑ": "Date",
        "ΕΥΗΝΟΣ":     "Eyinos",
        "ΜΑΡΑΘΩΝΑΣ":  "Marathonas",
        "ΜΟΡΝΟΣ":     "Mornos",
        "ΥΛΙΚΗ":      "Yliki",
        "ΣΥΝΟΛΟ":     "Synolo",
        "TOTAL":      "Total",
    })

    df["Date"] = pd.to_datetime(df["Date"].str.strip(), format="%d/%m/%Y")

    numeric_cols = ["Eyinos", "Marathonas", "Mornos", "Yliki", "Synolo", "Total"]
    for col in numeric_cols:
        df[col] = (
            df[col]
            .str.strip()
            .str.replace(".", "", regex=False)
            .str.replace(",", ".", regex=False)
            .astype(float)
            .astype(int)
        )

    # Drop the redundant TOTAL (= 2 × Synolo)
    df = df.drop(columns=["Total"])

    return df.reset_index(drop=True)


df = fetch_eydap_reservoir_rss()
df